spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/washer?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /washer
wechat:
  properties:
    APPID: wxe57e3d18ce05aba0
    APPSECRET: e0001636d768741a0075a63d6afd540d
    MCHID: 1544200541
    KEY: yjm2m012345678900987654321washer
    #网页授权获取code(用来换取授权accessToken)接口
    CODEURL: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect
    #网页授权获取accessToken接口
    ACCESS_TOKEN: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
    #请求获取user info接口
    USEER_INFO: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
    #获取全局token接口(与网页授权accessToken不是同一个!)
    TOKEN: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    #未关注用户,需要先扫二维码关注
    SUBSCRIBEURL: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkzOTAwMDYxMg==&scene=126&bizpsid=0#wechat_redirect
    #获取code拼接后的链接
    AUTHURL: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx08ebde9612580ab9&redirect_uri=http%3A%2F%2Fwjcdemo.natapp1.cc%2Flogin&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect
    UNIFIEDORDER: https://api.mch.weixin.qq.com/pay/unifiedorder
    ISSUBSCRIBEURL: https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
    #查询订单状态链接
    QUERYORDERURL: https://api.mch.weixin.qq.com/pay/orderquery
    #推送消息模板
    TEMPLATEURL: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=ACCESS_TOKEN
    #洗衣结束通知,模板ID
    FINISHEDTEMPLATEID: m24SyeKTxURGLD80zU9TgtMm_YetHHNWA69T53dyvBE
    #订单异常通知模板
    EXCEPTIONTEMPLATEID: ca1-HQ90AAoMo85sidJ-EQcnpJ_i0cWyYVejWxNhKOU
aliyun:
  properties:
    accessKey: LTAIXP8X2zp7tCUT
    accessSecret: AkQUqaG2mcIK0PfsajlwS2C01NhNuo
    productKey: a1BtlNaE1lQ